services:
  mongodb:
    image: mongo:6.0
    container_name: parcel_dash_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./backend
    container_name: parcel_dash_backend
    restart: always
    depends_on:
      - mongodb
    env_file:
      - .env
    ports:
      - "8000:8000"
      
  frontend:
    build: ./frontend
    container_name: parcel_dash_frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "8050:8050"


volumes:
  mongo_data:
  